spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
    pool-size: 30
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970